#!/bin/bash
# hooks/haproxy-relation-joined

export KUBERNETES_MASTER=`netstat -nap | grep apiserver | grep LISTEN | grep 8080 | awk '{print $4}'`

SERVICES='services=['

nodeServices=`kubectl get services -o template --template="{{range .items}}{{.spec.type}} {{.metadata.name}} {{range .spec.ports}}{{println .port .nodePort}}{{end}}{{end}}" | grep LoadBalancer | awk '{print $2 " " $3 " " $4}'`

#echo $nodeServices

SERVICES+=$(echo $nodeServices | while read svcName port nodePort; do

        count=1
        #handle each service

        SERVICES="{'service_name': '${svcName}',"
        SERVICES+=" 'service_host': '0.0.0.0',"
        SERVICES+=" 'service_port': '${port}',"

        SERVICES+=" 'service_options': ['mode http', 'balance roundrobin', 'option forwardfor'"
        #SERVICES+=", 'http-request set-header X-Forwarded-Port %[dst_port]'"

        #SERVICES+=", 'cookie SRV_ID prefix'"

        #SERVICES+=" 'service_options': [],"

        SERVICES+="],"

        SERVICES+=" 'servers': ["

        SERVICES+=$(kubectl get node | while read ip labels status ; do
                if [ $ip != "NAME" ]; then
                        echo "['${svcName}_${count}', '$ip', '$nodePort', 'check'],"
                        count=`expr $count + 1`
                fi
        done;)

        SERVICES+="]}"
        echo "$SERVICES"
done;)

SERVICES+="]"

#echo "!!!~Try to relation-set $SERVICES"

relation-set "$SERVICES"
