#!/bin/bash

set -eux

port=`relation-get port`
server_address=`relation-get hostname`

if [ -z "$server_address" ]; then
  juju-log "No data sent yet"
  exit 0
fi


# If you've gotten this far, you have a $server_address, configure as you see fit