options:
  zone:
    description: The DNS root zone for this service
    type: string
  smtp_server:
    default: ""
    description: The SMTP server to send password recovery emails from
    type: string
  smtp_username:
    default: ""
    description: Username to authenticate with the SMTP server
    type: string
  smtp_password:
    default: ""
    description: Password to authenticate with the SMTP server
    type: string
  email_sender:
    default: ""
    description: Email address to send recovery emails from
    type: string
  signup_key:
    description: The secret signup key used to create a new account
    type: string
  base_number:
    description: The first number to be allocated in the number range
    type: string
  number_count:
    default: 1
    description: The count of numbers to allocate
    type: int
  repo:
    default: http://repo.cw-ngv.com/juju-clearwater-1/
    description: The location of the repo server
    type: string
