options:
  zone:
    description: The DNS root zone for this manager
    type: string
  sas:
    default: ""
    description: The location of the SAS server
    type: string
  enum:
    default: ""
    description: The location of the ENUM server
    type: string
  access_key:
    description: EC2 Access Key
    type: string
  secret_key:
    description: EC2 Secret Access Key
    type: string
