#!/usr/bin/python
import os
import subprocess
import sys


# Add charmhelpers to the system path.
try:
    sys.path.insert(0, os.path.abspath(os.path.join(os.environ['CHARM_DIR'],
                                                    'lib')))
    sys.path.insert(0, os.path.abspath(os.path.join(os.environ['CHARM_DIR'],
                                                    'contrib')))
except:
    sys.path.insert(0, os.path.abspath(os.path.join('..', 'lib')))
    sys.path.insert(0, os.path.abspath(os.path.join('..', 'contrib')))


from charmhelpers.core.hookenv import (
    log,
    config,
)
from charmhelpers.fetch import (
    apt_install,
    apt_update,
)
from common import install_packages, sanity_check
from bind.install import ProviderInstaller


class Install(object):

    # Does not assume offline environment by default
    def install_core(self):
        if not sanity_check():
            return 0

        # TODO: Check offline, install fatpack
        if config()['offline'] is False:
            apt_update(fatal=True)
            apt_install(packages=['python-pip'], fatal=True)

            subprocess.call(['pip', 'install', '-r', 'requirements.txt',
                             '--upgrade'])
        else:
            log('Installing Core Packages from Offline Pack')
            install_packages('files/core')

    # Place the offline environment as a config option
    # Place the files in data/ and the provider/charm will look to isntall this
    # information from there.

    def install_provider(self):
        if config()['provider'] == 'bind':
            ProviderInstaller()
            ## use the nameserver in /etc/resolv.conf as a forwarder ...
            import DNS
            DNS.ParseResolvConf("/etc/resolv.conf")
            nameserver = DNS.defaults['server'][0]
            log('Setting dns to be forwarder to :'+nameserver)
            import jinja2
            templateLoader = jinja2.FileSystemLoader( searchpath= os.environ['CHARM_DIR'] )
            #use Jinja2 template to enable bind forwarding 
            templateEnv=jinja2.Environment( loader=templateLoader );
            template=templateEnv.get_template('contrib/bind/templates/named.conf.options.jinja2')
            output_from_parsed_template = template.render(forwarder=nameserver)
            # to save the results
            with open("/etc/bind/named.conf.options", "wb") as fh:
                fh.write(output_from_parsed_template)
                ## use jinja2 templates..


if __name__ == '__main__':
    i = Install()
    i.install_core()
    i.install_provider()
